"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional, Sequence
from fastapi.security.base import SecurityBase
from pydantic.fields import ModelField

param_supported_types = (str, int, float, bool)
class SecurityRequirement:
    def __init__(self, security_scheme: SecurityBase, scopes: Optional[Sequence[str]] = ...) -> None:
        ...
    


class Dependant:
    def __init__(self, *, path_params: Optional[List[ModelField]] = ..., query_params: Optional[List[ModelField]] = ..., header_params: Optional[List[ModelField]] = ..., cookie_params: Optional[List[ModelField]] = ..., body_params: Optional[List[ModelField]] = ..., dependencies: Optional[List[Dependant]] = ..., security_schemes: Optional[List[SecurityRequirement]] = ..., name: Optional[str] = ..., call: Optional[Callable] = ..., request_param_name: Optional[str] = ..., websocket_param_name: Optional[str] = ..., http_connection_param_name: Optional[str] = ..., response_param_name: Optional[str] = ..., background_tasks_param_name: Optional[str] = ..., security_scopes_param_name: Optional[str] = ..., security_scopes: Optional[List[str]] = ..., use_cache: bool = ..., path: Optional[str] = ...) -> None:
        ...
    


