"""
This type stub file was generated by pyright.
"""

from typing import Any

asynccontextmanager_error_message = """
FastAPI's contextmanager_in_threadpool require Python 3.7 or above,
or the backport for Python 3.6, installed with:
    pip install async-generator
"""


@asynccontextmanager
async def contextmanager_in_threadpool(cm: Any) -> Any:
    ...
