"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Sequence
from pydantic import ValidationError, create_model
from pydantic.error_wrappers import ErrorList
from starlette.exceptions import HTTPException as StarletteHTTPException

class HTTPException(StarletteHTTPException):
    def __init__(self, status_code: int, detail: Any = ..., headers: Optional[Dict[str, Any]] = ...) -> None:
        ...
    


RequestErrorModel = create_model("Request")
WebSocketErrorModel = create_model("WebSocket")
class FastAPIError(RuntimeError):
    """
    A generic, FastAPI-specific error.
    """
    ...


class RequestValidationError(ValidationError):
    def __init__(self, errors: Sequence[ErrorList], *, body: Any = ...) -> None:
        ...
    


class WebSocketRequestValidationError(ValidationError):
    def __init__(self, errors: Sequence[ErrorList]) -> None:
        ...
    


