"""
This type stub file was generated by pyright.
"""

from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException
from starlette.requests import Request
from starlette.responses import JSONResponse

async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    ...

async def request_validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    ...

