"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional, Sequence

def Path(default: Any, *, alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., deprecated: Optional[bool] = ..., **extra: Any) -> Any:
    ...

def Query(default: Any, *, alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., deprecated: Optional[bool] = ..., **extra: Any) -> Any:
    ...

def Header(default: Any, *, alias: Optional[str] = ..., convert_underscores: bool = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., deprecated: Optional[bool] = ..., **extra: Any) -> Any:
    ...

def Cookie(default: Any, *, alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., deprecated: Optional[bool] = ..., **extra: Any) -> Any:
    ...

def Body(default: Any, *, embed: bool = ..., media_type: str = ..., alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., **extra: Any) -> Any:
    ...

def Form(default: Any, *, media_type: str = ..., alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., **extra: Any) -> Any:
    ...

def File(default: Any, *, media_type: str = ..., alias: Optional[str] = ..., title: Optional[str] = ..., description: Optional[str] = ..., gt: Optional[float] = ..., ge: Optional[float] = ..., lt: Optional[float] = ..., le: Optional[float] = ..., min_length: Optional[int] = ..., max_length: Optional[int] = ..., regex: Optional[str] = ..., **extra: Any) -> Any:
    ...

def Depends(dependency: Optional[Callable] = ..., *, use_cache: bool = ...) -> Any:
    ...

def Security(dependency: Optional[Callable] = ..., *, scopes: Optional[Sequence[str]] = ..., use_cache: bool = ...) -> Any:
    ...

