"""
This type stub file was generated by pyright.
"""

from typing import Any
from starlette.responses import JSONResponse

class ORJSONResponse(JSONResponse):
    media_type = ...
    def render(self, content: Any) -> bytes:
        ...
    


