"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Type, Union
from fastapi import params
from fastapi.dependencies.models import Dependant
from fastapi.encoders import DictIntStrAny, SetIntStr
from pydantic.fields import ModelField
from starlette import routing
from starlette.responses import Response
from starlette.types import ASGIApp

async def serialize_response(*, field: Optional[ModelField] = ..., response_content: Any, include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ..., is_coroutine: bool = ...) -> Any:
    ...

async def run_endpoint_function(*, dependant: Dependant, values: Dict[str, Any], is_coroutine: bool) -> Any:
    ...

def get_request_handler(dependant: Dependant, body_field: Optional[ModelField] = ..., status_code: int = ..., response_class: Type[Response] = ..., response_field: Optional[ModelField] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., dependency_overrides_provider: Optional[Any] = ...) -> Callable:
    ...

def get_websocket_app(dependant: Dependant, dependency_overrides_provider: Optional[Any] = ...) -> Callable:
    ...

class APIWebSocketRoute(routing.WebSocketRoute):
    def __init__(self, path: str, endpoint: Callable, *, name: Optional[str] = ..., dependency_overrides_provider: Optional[Any] = ...) -> None:
        ...
    


class APIRoute(routing.Route):
    def __init__(self, path: str, endpoint: Callable, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., name: Optional[str] = ..., methods: Optional[Union[Set[str], List[str]]] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., dependency_overrides_provider: Optional[Any] = ..., callbacks: Optional[List[APIRoute]] = ...) -> None:
        ...
    
    def get_route_handler(self) -> Callable:
        ...
    


class APIRouter(routing.Router):
    def __init__(self, routes: Optional[List[routing.BaseRoute]] = ..., redirect_slashes: bool = ..., default: Optional[ASGIApp] = ..., dependency_overrides_provider: Optional[Any] = ..., route_class: Type[APIRoute] = ..., default_response_class: Optional[Type[Response]] = ..., on_startup: Optional[Sequence[Callable]] = ..., on_shutdown: Optional[Sequence[Callable]] = ...) -> None:
        ...
    
    def add_api_route(self, path: str, endpoint: Callable, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., methods: Optional[Union[Set[str], List[str]]] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., route_class_override: Optional[Type[APIRoute]] = ..., callbacks: Optional[List[APIRoute]] = ...) -> None:
        ...
    
    def api_route(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., methods: Optional[List[str]] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def add_api_websocket_route(self, path: str, endpoint: Callable, name: Optional[str] = ...) -> None:
        ...
    
    def websocket(self, path: str, name: Optional[str] = ...) -> Callable:
        ...
    
    def include_router(self, router: APIRouter, *, prefix: str = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., default_response_class: Optional[Type[Response]] = ...) -> None:
        ...
    
    def get(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def put(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def post(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def delete(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def options(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def head(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def patch(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    
    def trace(self, path: str, *, response_model: Optional[Type[Any]] = ..., status_code: int = ..., tags: Optional[List[str]] = ..., dependencies: Optional[Sequence[params.Depends]] = ..., summary: Optional[str] = ..., description: Optional[str] = ..., response_description: str = ..., responses: Optional[Dict[Union[int, str], Dict[str, Any]]] = ..., deprecated: Optional[bool] = ..., operation_id: Optional[str] = ..., response_model_include: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_exclude: Optional[Union[SetIntStr, DictIntStrAny]] = ..., response_model_by_alias: bool = ..., response_model_exclude_unset: bool = ..., response_model_exclude_defaults: bool = ..., response_model_exclude_none: bool = ..., include_in_schema: bool = ..., response_class: Optional[Type[Response]] = ..., name: Optional[str] = ..., callbacks: Optional[List[APIRoute]] = ...) -> Callable:
        ...
    


