"""
This type stub file was generated by pyright.
"""

from typing import Optional
from fastapi.security.base import SecurityBase
from starlette.requests import Request

class APIKeyBase(SecurityBase):
    ...


class APIKeyQuery(APIKeyBase):
    def __init__(self, *, name: str, scheme_name: Optional[str] = ..., auto_error: bool = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> Optional[str]:
        ...
    


class APIKeyHeader(APIKeyBase):
    def __init__(self, *, name: str, scheme_name: Optional[str] = ..., auto_error: bool = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> Optional[str]:
        ...
    


class APIKeyCookie(APIKeyBase):
    def __init__(self, *, name: str, scheme_name: Optional[str] = ..., auto_error: bool = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> Optional[str]:
        ...
    


