"""
This type stub file was generated by pyright.
"""

from fastapi.openapi.models import SecurityBase as SecurityBaseModel

class SecurityBase:
    model: SecurityBaseModel
    scheme_name: str
    ...


