"""
This type stub file was generated by pyright.
"""

from typing import Optional
from fastapi.security.base import SecurityBase
from starlette.requests import Request

class OpenIdConnect(SecurityBase):
    def __init__(self, *, openIdConnectUrl: str, scheme_name: Optional[str] = ..., auto_error: bool = ...) -> None:
        ...
    
    async def __call__(self, request: Request) -> Optional[str]:
        ...
    


