"""
This type stub file was generated by pyright.
"""

from typing import Optional
from starlette.responses import HTMLResponse

def get_swagger_ui_html(*, openapi_url: str, title: str, swagger_js_url: str = ..., swagger_css_url: str = ..., swagger_favicon_url: str = ..., oauth2_redirect_url: Optional[str] = ..., init_oauth: Optional[dict] = ...) -> HTMLResponse:
    ...

def get_redoc_html(*, openapi_url: str, title: str, redoc_js_url: str = ..., redoc_favicon_url: str = ..., with_google_fonts: bool = ...) -> HTMLResponse:
    ...

def get_swagger_ui_oauth2_redirect_html() -> HTMLResponse:
    ...

